# Generated by Django 6.0.1 on 2026-01-28 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_document_file_remove_message_thread_localchat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localchat',
            name='documents_used',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localchat',
            name='used_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
